# Generated by Django 4.2 on 2023-11-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('public', 'public'), ('portfolio', 'portfolio'), ('oms', 'oms'), ('ecommerce', 'ecommerce')], max_length=100),
        ),
    ]
