services:
  db:
    image: postgres:16
    env_file: ./src/.env
    container_name: bepasal-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    container_name: bepasal-redis
    image: redis:latest
    ports:
      - "6379:6379"

  bepasal-web:
    container_name: bepasal-web
    env_file: ./src/.env
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "watchmedo auto-restart --patterns='*.py' --recursive -- python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  esdata:
    driver: local
