# Generated by Django 5.0.6 on 2024-06-29 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='system.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='system.orderstatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fonepay_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='system.fonepaypayment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='system.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='system.category'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='system.product'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='system.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_product', to='system.productvariation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='system.productvariation'),
        ),
        migrations.AddField(
            model_name='productvariationimage',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='system.productvariation'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='taxes_applied',
            field=models.ManyToManyField(blank=True, to='system.tax'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_option_combination',
            field=models.ManyToManyField(blank=True, related_name='variations', to='system.variationoption'),
        ),
        migrations.AddField(
            model_name='variationoption',
            name='variation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='system.variationtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='enabled_variation_types',
            field=models.ManyToManyField(blank=True, to='system.variationtype'),
        ),
    ]
