# Generated by Django 4.2 on 2024-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='first_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='last_name',
            new_name='given_name',
        ),
        migrations.RemoveField(
            model_name='userbase',
            name='gender',
        ),
    ]
