# Generated by Django 4.2 on 2024-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userbase_city_alter_userbase_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='display_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_display_images'),
        ),
    ]
