# Generated by Django 4.1.5 on 2023-09-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='hash',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=204335, max_length=6),
        ),
    ]
