# Generated by Django 5.0.6 on 2024-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_variations',
            field=models.ManyToManyField(to='system.productvariation'),
        ),
    ]
