# Generated by Django 4.2 on 2023-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oms', '0001_initial'),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_variations',
            field=models.ManyToManyField(blank=True, to='oms.productvariation'),
        ),
    ]
