# Generated by Django 4.2 on 2024-03-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_variations',
            field=models.ManyToManyField(blank=True, to='system.productvariation'),
        ),
    ]
