# Generated by Django 4.2 on 2023-12-10 12:32

import core.utils.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_initial'),
        ('ecommerce', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oms.productvariation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='quantities',
            field=models.JSONField(default=core.utils.functions.default_json),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
