# Generated by Django 4.2 on 2023-12-10 18:37

import core.utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_cart_product_variation_cart_quantities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantities',
            field=models.JSONField(blank=True, default=core.utils.functions.default_json, null=True),
        ),
    ]
