# Generated by Django 4.2 on 2023-12-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_productvariation_slug'),
        ('ecommerce', '0006_alter_cart_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_variations',
            field=models.ManyToManyField(to='oms.productvariation'),
        ),
    ]
