# Generated by Django 4.2 on 2023-11-14 07:53

import ckeditor.fields
import core.utils.functions
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import oms.models.item
import oms.models.review


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('crossed_price', models.PositiveBigIntegerField(default=0)),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('continue_selling_after_out_of_stock', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_image', models.ImageField(upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('crossed_price', models.PositiveBigIntegerField(default=0)),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_contact', models.CharField(default='', max_length=255)),
                ('delivery_note', models.CharField(default='', max_length=255)),
                ('delivery_location', models.CharField(default='', max_length=255)),
                ('geo_tag', models.JSONField(default=core.utils.functions.default_json)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('total_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('extra_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_remarks', models.CharField(default='', max_length=255)),
                ('total_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_remarks', models.TextField(blank=True, default='')),
                ('refunded_remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('variation', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_remarks', models.CharField(default='', max_length=255)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_remarks', models.TextField(blank=True, default='')),
                ('returned_remarks', models.TextField(blank=True, default='')),
                ('refunded_remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subtract_from_inventory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subtract_from_inventory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=oms.models.review.image_directory_path)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='oms.variationtype')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('stars', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('images', models.ManyToManyField(to='oms.reviewimage')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
    ]
