# Generated by Django 4.2 on 2023-11-15 13:12

import ckeditor.fields
import core.utils.functions
from django.db import migrations, models
import django.db.models.deletion
import oms.models.item


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FonePayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_status', models.CharField(choices=[('initiated', 'initiated'), ('requested', 'requested'), ('failed', 'failed'), ('success', 'success')], default='initiated', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('last_response_from_fonepay', models.TextField(blank=True, null=True)),
                ('invoice_number', models.CharField(max_length=255)),
                ('is_verified_from_server', models.BooleanField(default=False)),
                ('trace_id', models.TextField(blank=True, default='', null=True)),
                ('ird_details_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('crossed_price', models.PositiveBigIntegerField(default=0)),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('continue_selling_after_out_of_stock', models.BooleanField(default=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_image', models.ImageField(upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.PositiveIntegerField(default=0)),
                ('crossed_price', models.PositiveBigIntegerField(default=0)),
                ('cost_price', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variation', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=oms.models.item.image_directory_path)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('user_contact', models.CharField(default='', max_length=255)),
                ('delivery_note', models.CharField(default='', max_length=255)),
                ('delivery_location', models.CharField(default='', max_length=255)),
                ('geo_tag', models.JSONField(default=core.utils.functions.default_json)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('total_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('extra_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_remarks', models.CharField(default='', max_length=255)),
                ('total_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancellation_remarks', models.TextField(blank=True, default='')),
                ('refunded_remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subtract_from_inventory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subtract_from_inventory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='oms.variationtype')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('fonepay', 'Fonepay'), ('staff_approved', 'Staff Approved')], default='fonepay', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=60)),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_remarks', models.TextField(blank=True, default='')),
                ('fonepay_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oms.fonepaypayment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='oms.order')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('variation', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('discount_remarks', models.CharField(default='', max_length=255)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_remarks', models.TextField(blank=True, default='')),
                ('returned_remarks', models.TextField(blank=True, default='')),
                ('refunded_remarks', models.TextField(blank=True, default='')),
                ('item_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='oms.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='oms.order')),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='oms.orderstatus'),
        ),
    ]
