# Generated by Django 4.2 on 2023-11-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvariation',
            name='variation',
        ),
        migrations.RemoveField(
            model_name='itemvariation',
            name='variation_type',
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='variation_type',
            field=models.ManyToManyField(related_name='variations', to='oms.variationoption'),
        ),
    ]
