# Generated by Django 4.2 on 2023-12-04 17:34

from django.db import migrations, models
import oms.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_item_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='auto_complete_digital_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to=oms.models.product.file_directory_path),
        ),
    ]
