# Generated by Django 4.2 on 2023-12-16 19:03

from django.db import migrations, models
import oms.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=oms.models.product.image_directory_path2),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=oms.models.product.image_directory_path2),
        ),
        migrations.AlterField(
            model_name='productvariationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=oms.models.product.image_directory_path3),
        ),
    ]
