# Generated by Django 4.2 on 2023-12-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0003_productvariation_thumbnail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_item_digital',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
