# Generated by Django 4.2 on 2023-11-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='variation_type',
            new_name='variation',
        ),
        migrations.AddField(
            model_name='item',
            name='enabled_variation_types',
            field=models.ManyToManyField(blank=True, to='oms.variationtype'),
        ),
    ]
