# Generated by Django 4.2 on 2023-12-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0004_remove_product_is_item_digital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='is_default_variation',
        ),
        migrations.AddField(
            model_name='product',
            name='default_variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_product', to='oms.productvariation'),
        ),
    ]
