# Generated by Django 4.2 on 2023-11-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0005_rename_variation_type_itemvariation_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='variation',
            new_name='variation_combination',
        ),
    ]
