# Generated by Django 4.2 on 2023-11-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_rename_variation_itemvariation_variation_combination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvariation',
            old_name='variation_combination',
            new_name='variation_option_combination',
        ),
    ]
