# Generated by Django 4.2 on 2023-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0006_tax_productvariation_stock_unit_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='stock_unit_in',
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
