# Generated by Django 4.2 on 2023-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0007_rename_variation_combination_itemvariation_variation_option_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extra_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=60),
        ),
    ]
