# Generated by Django 4.2 on 2023-11-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0008_alter_order_extra_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_eligible_for_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='is_eligible_for_discount',
            field=models.BooleanField(default=True),
        ),
    ]
