# Generated by Django 4.2 on 2023-11-18 21:35

from django.db import migrations, models
import oms.models.item


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0009_item_is_eligible_for_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='crossed_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_eligible_for_discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.AlterField(
            model_name='item',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=oms.models.item.image_directory_path),
        ),
    ]
