# Generated by Django 4.2 on 2023-11-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0010_remove_item_cost_price_remove_item_crossed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvariation',
            name='is_default_variation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemvariation',
            name='variation_option_combination',
            field=models.ManyToManyField(blank=True, related_name='variations', to='oms.variationoption'),
        ),
    ]
