# Generated by Django 4.2 on 2023-11-25 16:55

import core.utils.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0012_remove_orderitem_item_instance_orderitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-is_active', '-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itemvariation',
            name='is_eligible_for_discounts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='backup_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='extra_fields',
            field=models.JSONField(default=core.utils.functions.default_json),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='geo_tag',
            field=models.JSONField(blank=True, default=core.utils.functions.default_json),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oms.deliverymethod'),
        ),
    ]
