# Generated by Django 4.2 on 2023-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0013_deliverymethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
