# Generated by Django 4.2 on 2023-12-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms', '0014_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='catagories',
            new_name='categories',
        ),
    ]
